version: "3.8"

services:
  # Aplicación Laravel (PHP FPM)
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: integral_laravel_prod_app
    restart: always
    working_dir: /var/www
    volumes:
      # En producción solo persistimos storage para uploads/logs
      - storage_data:/var/www/storage
      - app_public:/var/www/public
    env_file:
      - .env
    environment:
      APP_ENV: production
      APP_DEBUG: "false"
    networks:
      - dokploy-network

  # Servidor Web Nginx
  web:
    image: nginx:alpine
    container_name: integral_nginx_prod_front
    restart: always
    ports:
      - "8080:80"
    volumes:
      # Mapeo de código/public y logs
      - app_public:/var/www/public:ro
      - ./docker/nginx/prod.conf/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - dokploy-network

networks:
  dokploy-network:
    driver: bridge

volumes:
  storage_data:
  app_public: