/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './resources/**/*.blade.php',
        './resources/**/*.js',
    ],
    safelist: [
        // Colores del banco - explícitos
        'bg-[#003B71]', 'bg-[#E97300]', 'bg-[#dce8f5]', 'bg-[#002a52]', 'bg-[#c96200]',
        'text-[#003B71]', 'text-[#E97300]', 'text-[#dce8f5]', 'text-[#002a52]', 'text-[#ffffff]',
        'border-[#003B71]', 'border-[#E97300]', 'border-[#dce8f5]',
        'hover:bg-[#003B71]', 'hover:bg-[#E97300]', 'hover:bg-[#dce8f5]', 'hover:bg-[#002a52]',
        'hover:text-[#003B71]', 'hover:text-[#E97300]', 'hover:text-[#ffffff]',
        // Opacidades
        { pattern: /bg-(white|black)\/(10|20|30|50)/ },
        { pattern: /border-white\/(20|30)/ },
        // Spacing
        { pattern: /^p-(4|5|6|8|12)$/ },
        { pattern: /^px-(4|5|6|8)$/ },
        { pattern: /^py-(2|3|6|8|12|16|20)$/ },
        { pattern: /^gap-(1|2|3|4|5|6|8|12)$/ },
        { pattern: /^mb-(3|4|6|8|12)$/ },
        { pattern: /^text-(xs|sm|base|lg|xl|2xl|4xl|5xl)$/ },
        { pattern: /^font-(medium|semibold|bold)$/ },
        { pattern: /^leading-(relaxed|tight|snug)$/ },
        { pattern: /^w-(11|12|14|16|20|full)$/ },
        { pattern: /^h-(11|12|14|16|20)$/ },
        { pattern: /^rounded-(lg|xl|2xl|full)$/ },
        { pattern: /^grid-cols-(1|2|3|4)$/ },
        { pattern: /^order-(1|2)$/ },
        { pattern: /^text-gray-(200|300|600|700|900)$/ },
        { pattern: /^bg-gray-(50|100|200)$/ },
        { pattern: /^border-gray-(200|300)$/ },
        // Misc
        'flex', 'grid', 'hidden', 'block', 'inline-block', 'relative',
        'absolute', 'overflow-hidden', 'overflow-y-auto', 'shrink-0',
        'items-center', 'items-start', 'items-stretch',
        'justify-center', 'justify-between',
        'text-center', 'text-left', 'text-white',
        'mx-auto', 'mt-auto', 'border', 'border-2',
        'transition-all', 'duration-200', 'duration-300',
        'cursor-pointer', 'pointer-events-none',
        'shadow-lg', 'shadow-xl', 'shadow-2xl',
        'object-cover', 'object-contain',
        'inset-0', 'z-10', 'z-20',
        '-translate-y-1/2', '-translate-x-1/2',
        'animate-spin', 'space-y-3', 'space-y-4',
        'hover:opacity-90', 'hover:shadow-xl', 'hover:underline',
        'hover:scale-110', 'hover:bg-gray-100',
        'sm:flex-row', 'lg:flex-row', 'lg:w-1/3', 'lg:w-2/3',
        'bg-white', 'bg-transparent',
        'border-gray-200', 'border-gray-300',
        'max-w-6xl', 'max-w-2xl', 'max-w-7xl',
        'w-full', 'h-full', 'min-h-screen',
        'py-12', 'px-6', 'p-6', 'p-8',
        'mb-12', 'mb-8', 'mb-4', 'mb-3', 'mt-4',
        'gap-4', 'gap-6', 'gap-12',
        'flex-col', 'flex-row', 'flex-wrap', 'flex-1',
        'text-4xl', 'text-base', 'font-bold', 'font-semibold',
        'leading-relaxed', 'leading-tight',
        'bg-white/10', 'bg-white/20', 'bg-white/30', 'bg-black/50',
        'border-white/20', 'border-white/30',
        'rounded-2xl', 'rounded-xl', 'rounded-lg', 'rounded-full',
    ],
    theme: {
        extend: {},
    },
    plugins: [],
};
