/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './resources/**/*.blade.php',
        './resources/**/*.js',
    ],
    safelist: [
        'bg-[#003B71]', 'bg-[#E97300]', 'bg-[#dce8f5]', 'bg-[#002a52]', 'bg-[#c96200]',
        'text-[#003B71]', 'text-[#E97300]', 'text-[#dce8f5]', 'text-[#002a52]', 'text-[#ffffff]',
        'border-[#003B71]', 'border-[#E97300]', 'border-[#dce8f5]',
        'hover:bg-[#003B71]', 'hover:bg-[#E97300]', 'hover:bg-[#dce8f5]', 'hover:bg-[#002a52]',
        'hover:text-[#003B71]', 'hover:text-[#E97300]', 'hover:text-[#ffffff]',
        'hover:bg-[#dce8f5]', 'hover:text-[#003B71]',
        { pattern: /bg-(white|black)\/(10|20|30|50)/ },
        { pattern: /border-white\/(20|30)/ },
        { pattern: /^p-(0|1|2|3|4|5|6|7|8|10|12|16)$/ },
        { pattern: /^px-(0|1|2|3|4|5|6|7|8|10|12|16)$/ },
        { pattern: /^py-(0|1|2|3|4|5|6|7|8|10|12|16|20)$/ },
        { pattern: /^pt-(0|1|2|3|4|5|6|8|10|12|16)$/ },
        { pattern: /^pb-(0|1|2|3|4|5|6|8|10|12|16)$/ },
        { pattern: /^pl-(0|1|2|3|4|5|6|8|10|12)$/ },
        { pattern: /^pr-(0|1|2|3|4|5|6|8|10|12)$/ },
        { pattern: /^m-(0|1|2|3|4|5|6|8|10|12|auto)$/ },
        { pattern: /^mx-(0|1|2|3|4|5|6|8|auto)$/ },
        { pattern: /^my-(0|1|2|3|4|5|6|8|10|12)$/ },
        { pattern: /^mt-(0|1|2|3|4|5|6|7|8|10|12|16|auto)$/ },
        { pattern: /^mb-(0|1|2|3|4|5|6|7|8|10|12|16)$/ },
        { pattern: /^ml-(0|1|2|3|4|5|6|8|auto)$/ },
        { pattern: /^mr-(0|1|2|3|4|5|6|8|auto)$/ },
        { pattern: /^gap-(0|1|2|3|4|5|6|7|8|10|12|16)$/ },
        { pattern: /^gap-x-(0|1|2|3|4|5|6|8|10|12)$/ },
        { pattern: /^gap-y-(0|1|2|3|4|5|6|8|10|12)$/ },
        { pattern: /^text-(xs|sm|base|lg|xl|2xl|3xl|4xl|5xl|6xl|7xl|8xl)$/ },
        { pattern: /^font-(thin|light|normal|medium|semibold|bold|extrabold|black)$/ },
        { pattern: /^leading-(none|tight|snug|normal|relaxed|loose)$/ },
        { pattern: /^tracking-(tighter|tight|normal|wide|wider|widest)$/ },
        { pattern: /^w-(0|1|2|3|4|5|6|7|8|9|10|11|12|14|16|20|24|32|40|48|64|auto|full|screen|min|max|fit)$/ },
        { pattern: /^h-(0|1|2|3|4|5|6|7|8|9|10|11|12|14|16|20|24|32|40|48|64|auto|full|screen|min|max|fit)$/ },
        { pattern: /^min-h-(0|full|screen|min|max|fit)$/ },
        { pattern: /^max-w-(xs|sm|md|lg|xl|2xl|3xl|4xl|5xl|6xl|7xl|full|screen|min|max|fit|none|prose)$/ },
        { pattern: /^max-h-(0|full|screen|min|max|fit|none)$/ },
        { pattern: /^rounded-(none|sm|md|lg|xl|2xl|3xl|full)$/ },
        { pattern: /^rounded-(t|b|l|r|tl|tr|bl|br)-(none|sm|md|lg|xl|2xl|3xl|full)$/ },
        { pattern: /^border-(0|1|2|4|8)$/ },
        { pattern: /^border-(t|b|l|r)-(0|1|2|4)$/ },
        { pattern: /^border-gray-(100|200|300|400|500)$/ },
        { pattern: /^bg-gray-(50|100|200|300|400|500)$/ },
        { pattern: /^text-gray-(100|200|300|400|500|600|700|800|900)$/ },
        { pattern: /^opacity-(0|5|10|20|25|30|40|50|60|70|75|80|90|95|100)$/ },
        { pattern: /^grid-cols-(1|2|3|4|5|6|7|8|9|10|11|12|none)$/ },
        { pattern: /^col-span-(1|2|3|4|5|6|7|8|9|10|11|12|full)$/ },
        { pattern: /^row-span-(1|2|3|4|5|6|full)$/ },
        { pattern: /^order-(1|2|3|4|5|6|7|8|9|10|11|12|first|last|none)$/ },
        { pattern: /^z-(0|10|20|30|40|50|auto)$/ },
        { pattern: /^inset-(0|auto|x|y)$/ },
        { pattern: /^top-(0|1|2|3|4|5|6|8|10|12|16|auto|full)$/ },
        { pattern: /^bottom-(0|1|2|3|4|5|6|8|10|12|16|auto|full)$/ },
        { pattern: /^left-(0|1|2|3|4|5|6|8|10|12|16|auto|full)$/ },
        { pattern: /^right-(0|1|2|3|4|5|6|8|10|12|16|auto|full)$/ },
        { pattern: /^translate-(x|y)-(.+)$/ },
        { pattern: /^scale-(0|50|75|90|95|100|105|110|125|150)$/ },
        { pattern: /^rotate-(0|1|2|3|6|12|45|90|180)$/ },
        { pattern: /^duration-(75|100|150|200|300|500|700|1000)$/ },
        { pattern: /^ease-(linear|in|out|in-out)$/ },
        { pattern: /^shadow-(none|sm|md|lg|xl|2xl|inner)$/ },
        { pattern: /^aspect-(auto|square|video)$/ },
        { pattern: /^object-(contain|cover|fill|none|scale-down)$/ },
        { pattern: /^object-(bottom|center|left|right|top)$/ },
        { pattern: /^overflow-(auto|hidden|visible|scroll|x-auto|y-auto|x-hidden|y-hidden)$/ },
        'flex', 'inline-flex', 'grid', 'block', 'inline-block', 'inline', 'hidden', 'contents',
        'flex-col', 'flex-row', 'flex-col-reverse', 'flex-row-reverse',
        'flex-wrap', 'flex-nowrap', 'flex-wrap-reverse',
        'flex-1', 'flex-auto', 'flex-none', 'flex-shrink', 'flex-shrink-0', 'flex-grow', 'flex-grow-0',
        'items-start', 'items-center', 'items-end', 'items-stretch', 'items-baseline',
        'justify-start', 'justify-center', 'justify-end', 'justify-between', 'justify-around', 'justify-evenly',
        'self-start', 'self-center', 'self-end', 'self-stretch', 'self-auto',
        'text-left', 'text-center', 'text-right', 'text-justify',
        'text-white', 'text-black',
        'font-bold', 'font-semibold', 'font-medium', 'font-normal', 'font-extrabold',
        'leading-relaxed', 'leading-tight', 'leading-snug', 'leading-normal', 'leading-loose',
        'tracking-wide', 'tracking-wider', 'tracking-widest', 'tracking-tight',
        'underline', 'line-through', 'no-underline',
        'uppercase', 'lowercase', 'capitalize', 'normal-case',
        'italic', 'not-italic',
        'whitespace-normal', 'whitespace-nowrap', 'whitespace-pre', 'whitespace-pre-wrap',
        'break-words', 'break-all', 'break-normal',
        'truncate', 'text-ellipsis', 'text-clip',
        'bg-white', 'bg-black', 'bg-transparent',
        'bg-white/10', 'bg-white/20', 'bg-white/30', 'bg-black/50',
        'border', 'border-2', 'border-4',
        'border-white', 'border-black', 'border-transparent',
        'border-white/20', 'border-white/30',
        'border-gray-200', 'border-gray-300',
        'border-solid', 'border-dashed', 'border-dotted', 'border-none',
        'rounded', 'rounded-none', 'rounded-sm', 'rounded-md', 'rounded-lg', 'rounded-xl', 'rounded-2xl', 'rounded-3xl', 'rounded-full',
        'w-full', 'w-auto', 'w-screen', 'h-full', 'h-auto', 'h-screen',
        'min-h-screen', 'min-w-full',
        'max-w-full', 'max-w-none',
        'mx-auto', 'my-auto', 'mt-auto', 'mb-auto', 'ml-auto', 'mr-auto',
        'relative', 'absolute', 'fixed', 'sticky', 'static',
        'inset-0', 'inset-x-0', 'inset-y-0',
        'overflow-hidden', 'overflow-visible', 'overflow-auto', 'overflow-y-auto', 'overflow-x-hidden',
        'pointer-events-none', 'pointer-events-auto',
        'cursor-pointer', 'cursor-default', 'cursor-not-allowed',
        'select-none', 'select-text', 'select-all',
        'object-cover', 'object-contain', 'object-fill',
        'object-center', 'object-top', 'object-bottom',
        'shadow', 'shadow-sm', 'shadow-md', 'shadow-lg', 'shadow-xl', 'shadow-2xl', 'shadow-none',
        'transition', 'transition-all', 'transition-colors', 'transition-opacity', 'transition-transform',
        'duration-150', 'duration-200', 'duration-300', 'duration-500',
        'ease-in', 'ease-out', 'ease-in-out',
        'animate-spin', 'animate-pulse', 'animate-bounce',
        'opacity-0', 'opacity-50', 'opacity-75', 'opacity-100',
        'z-0', 'z-10', 'z-20', 'z-30', 'z-40', 'z-50',
        'shrink-0', 'shrink',
        'space-y-1', 'space-y-2', 'space-y-3', 'space-y-4', 'space-y-6', 'space-y-8',
        'space-x-1', 'space-x-2', 'space-x-3', 'space-x-4', 'space-x-6',
        'divide-y', 'divide-x', 'divide-gray-100', 'divide-gray-200',
        'hover:opacity-90', 'hover:opacity-80',
        'hover:shadow-lg', 'hover:shadow-xl',
        'hover:underline',
        'hover:scale-105', 'hover:scale-110',
        'hover:bg-gray-50', 'hover:bg-gray-100', 'hover:bg-white',
        'hover:text-white', 'hover:text-black',
        'hover:border-gray-300',
        'focus:outline-none', 'focus:ring-2', 'focus:ring-offset-2',
        'sm:flex', 'sm:hidden', 'sm:block',
        'sm:flex-row', 'sm:flex-col',
        'sm:grid-cols-2', 'sm:grid-cols-3',
        'sm:text-left', 'sm:text-center',
        'sm:px-6', 'sm:py-8', 'sm:p-6', 'sm:p-8',
        'md:flex', 'md:hidden', 'md:block',
        'md:flex-row', 'md:flex-col',
        'md:grid-cols-2', 'md:grid-cols-3', 'md:grid-cols-4',
        'md:px-8', 'md:py-12', 'md:p-8',
        'md:text-left', 'md:text-4xl', 'md:text-5xl',
        'lg:flex', 'lg:hidden', 'lg:block',
        'lg:flex-row', 'lg:flex-col',
        'lg:grid-cols-2', 'lg:grid-cols-3', 'lg:grid-cols-4',
        'lg:w-1/2', 'lg:w-1/3', 'lg:w-2/3',
        'lg:px-16', 'lg:py-16', 'lg:p-12',
        'lg:text-left', 'lg:text-5xl', 'lg:text-6xl',
        'xl:grid-cols-3', 'xl:grid-cols-4', 'xl:grid-cols-5',
        'xl:px-20', 'xl:py-20',
    ],
    theme: {
        extend: {},
    },
    plugins: [],
};